version: '3'
services:
  it-dev:
    image: node:10-slim
    container_name: it-dev
    user: "node"
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    command:
      sh -c 'npm install && npm run serve'
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  # it-docs:
  #   image: node:10-slim
  #   container_name: it-docs
  #   user: "node"
  #   working_dir: /home/node/app
  #   volumes:
  #     - .:/home/node/app
  #   entrypoint:
  #     - npm
  #     - run
  #     - docs:dev
  #   # command:
  #   #   sh -c 'npm run docs:dev'
  #   ports:
  #     - "8081:8080"
  #   environment:
  #     - NODE_ENV=development
  #   depends_on:
  #     - it-dev
