version: '3'
services:
  cita-dev:
    image: node:10-slim
    container_name: cita-dev
    user: "node"
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    command:
      sh -c 'npm install && npm run serve'
    ports:
      - "8080:8080"
